---
# tasks file for docker-engine

- name: Check ubuntu version is supported
  fail:
    msg: 'Ubuntu {{ ansible_lsb.codename }} not supported'
  when: ansible_lsb.codename not in docker_engine_supported
  tags:
    - docker_engine

- name: Update apt cache
  apt:
    update_cache: 'yes'
    cache_valid_time: '3600'
  register: apt_update_cache
  changed_when: apt_update_cache.cache_updated
  tags:
    - docker_engine

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'installed'
  with_items:
    - apt-transport-https
    - ca-certificates
  tags:
    - docker_engine

- name: Install required packages for prod environment
  apt:
    name: '{{ item }}'
    state: 'installed'
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
  when: docker_engine_is_prod and ansible_distribution_version | version_compare('16.04', '<')
  tags:
    - docker_engine

- name: Add docker apt key
  apt_key:
    keyserver: 'hkp://p80.pool.sks-keyservers.net:80'
    id: '58118E89F3A912897C070ADBF76221572C52609D'
  tags:
    - docker_engine

- name: Add docker repo
  apt_repository:
    filename: 'docker'
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_lsb.codename }} main'
  tags:
    - docker_engine

- name: Prevent docker to start on install
  copy:
    content: |-
      #!/bin/sh
      exit 101
    dest: '/usr/sbin/policy-rc.d'
    owner: 'root'
    group: 'root'
    mode: '0755'
  changed_when: False

- name: Install docker-engine
  apt:
    name: '{{ docker_engine_package_name }}'
    state: 'installed'
  tags:
    - docker_engine

- name: Remove policy-rc.d
  file:
    name: '/usr/sbin/policy-rc.d'
    state: 'absent'
  changed_when: False

- include: '{{ docker_engine_init_system }}.yml'
  tags:
    - docker_engine
