- name: Set docker defaults
  template:
    src: 'default_docker'
    dest: '/etc/default/docker'
    mode: '0644'
  notify: restart docker

- name: Ensure docker is started and enabled at boot
  service:
    name: 'docker'
    state: 'started'
    enabled: 'yes'
