- name: Set docker defaults
  template:
    src: 'default_docker'
    dest: '/etc/default/docker'
    mode: '0644'
  notify: restart docker

- name: Ensure docker is {{ docker_engine_state }} and enabled at boot
  service:
    name: 'docker'
    state: '{{ docker_engine_state }}'
    enabled: '{{ docker_engine_enabled }}'
