---
# handlers file for docker-engine

- name: restart docker
  service:
    name: 'docker'
    state: 'restarted'
  when: docker_engine_state == 'started'

- name: reload systemctl docker
  shell: >
    systemctl daemon-reload
  notify: restart docker
  when: docker_engine_state == 'started'
